//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJIntegral.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EJIntegralDBEntities : DbContext
    {
        public EJIntegralDBEntities()
            : base("name=EJIntegralDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BiometricInfo> BiometricInfoes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<DevelopmentArea> DevelopmentAreas { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Emp_Allowances> Emp_Allowances { get; set; }
        public virtual DbSet<Emp_Postions> Emp_Postions { get; set; }
        public virtual DbSet<Emp_Salaries> Emp_Salaries { get; set; }
        public virtual DbSet<LocalGovernment> LocalGovernments { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<Service_Details> Service_Details { get; set; }
        public virtual DbSet<Staff_Details> Staff_Details { get; set; }
        public virtual DbSet<StaffImage> StaffImages { get; set; }
    
        public virtual ObjectResult<Nullable<int>> CheckBiometricTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckBiometricTable");
        }
    
        public virtual ObjectResult<GetAllBanks_Result> GetAllBanks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllBanks_Result>("GetAllBanks");
        }
    
        public virtual ObjectResult<GetAllDAS_Result> GetAllDAS(Nullable<int> lgaId)
        {
            var lgaIdParameter = lgaId.HasValue ?
                new ObjectParameter("lgaId", lgaId) :
                new ObjectParameter("lgaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllDAS_Result>("GetAllDAS", lgaIdParameter);
        }
    
        public virtual ObjectResult<GetAllDepartment_Result> GetAllDepartment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllDepartment_Result>("GetAllDepartment");
        }
    
        public virtual ObjectResult<GetAllDesignations_Result> GetAllDesignations(Nullable<int> deptId)
        {
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("deptId", deptId) :
                new ObjectParameter("deptId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllDesignations_Result>("GetAllDesignations", deptIdParameter);
        }
    
        public virtual ObjectResult<GetAllLGAS_Result> GetAllLGAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllLGAS_Result>("GetAllLGAS");
        }
    
        public virtual ObjectResult<GetAllowanceByDesignationId_Result> GetAllowanceByDesignationId(Nullable<int> designationId)
        {
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("designationId", designationId) :
                new ObjectParameter("designationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllowanceByDesignationId_Result>("GetAllowanceByDesignationId", designationIdParameter);
        }
    
        public virtual int GetAllPositionsByDeptId(Nullable<int> deptId)
        {
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("deptId", deptId) :
                new ObjectParameter("deptId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAllPositionsByDeptId", deptIdParameter);
        }
    
        public virtual ObjectResult<GetAllQualifications_Result> GetAllQualifications()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllQualifications_Result>("GetAllQualifications");
        }
    
        public virtual ObjectResult<GetEmployeeInfo_Result> GetEmployeeInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeInfo_Result>("GetEmployeeInfo");
        }
    
        public virtual ObjectResult<GetEmployeeInfoForPrint_Result> GetEmployeeInfoForPrint(string staffId)
        {
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeInfoForPrint_Result>("GetEmployeeInfoForPrint", staffIdParameter);
        }
    
        public virtual ObjectResult<GetEmployeeInfoWithPhoto_Result> GetEmployeeInfoWithPhoto(string staffId)
        {
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeInfoWithPhoto_Result>("GetEmployeeInfoWithPhoto", staffIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetMaxId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetMaxId");
        }
    
        public virtual ObjectResult<Nullable<double>> GetSalaryByGradeAndStep(Nullable<int> grade, Nullable<int> step)
        {
            var gradeParameter = grade.HasValue ?
                new ObjectParameter("grade", grade) :
                new ObjectParameter("grade", typeof(int));
    
            var stepParameter = step.HasValue ?
                new ObjectParameter("step", step) :
                new ObjectParameter("step", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GetSalaryByGradeAndStep", gradeParameter, stepParameter);
        }
    
        public virtual ObjectResult<string> GetStaffId(string staffId)
        {
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetStaffId", staffIdParameter);
        }
    
        public virtual ObjectResult<sp_EmployeeInfoForPrint_Result> sp_EmployeeInfoForPrint(string staffId)
        {
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EmployeeInfoForPrint_Result>("sp_EmployeeInfoForPrint", staffIdParameter);
        }
    }
}
