//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJIntegral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Salaries
    {
        public int Id { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> Step { get; set; }
    }
}
