//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJIntegral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Details
    {
        public int Id { get; set; }
        public string StaffId { get; set; }
        public string FileNo { get; set; }
        public string Entry_Rank { get; set; }
        public System.DateTime DateOfFirstAppt { get; set; }
        public string Entry_GradeLevel { get; set; }
        public int Deparment { get; set; }
        public int Designation { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string BVN { get; set; }
        public Nullable<double> ConsolidatedSalary { get; set; }
        public string PlaceOfPosting { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<int> YearOfLastPromotion { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Qualification { get; set; }
        public Nullable<int> Step { get; set; }
        public Nullable<double> Allowances { get; set; }
        public string CurrentRank { get; set; }
        public string CurrentQualification { get; set; }
        public string CurrentGradeLevel { get; set; }
        public Nullable<int> CurrentStep { get; set; }
        public string SignatoryToApptLetter { get; set; }
        public Nullable<double> CurrentConsolidatedSalary { get; set; }
        public Nullable<int> CurrentDesignation { get; set; }
    }
}
