//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJIntegral.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Service_Details
    {
        public int Id { get; set; }
        public string StaffId { get; set; }
        [Display(Name ="File Number")]
        [Required]
        public string FileNo { get; set; }
        [Display(Name = "Entry Rank")]
        [Required]
        public string Entry_Rank { get; set; }
        [Display(Name = "Date of First Appointment")]
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime DateOfFirstAppt { get; set; }
        [Display(Name = "Entry Grade Level")]
        [Required]
        public string Entry_GradeLevel { get; set; }
        public int Deparment { get; set; }
        public int Designation { get; set; }
        [Display(Name = "Bank Name")]
        //[Required]
        public string BankName { get; set; }
        [Display(Name = "Account NUmber")]
        //[Required]
        public string AccountNumber { get; set; }
        [Display(Name = "Bank Verification Number")]
        //[Required]
        public string BVN { get; set; }
        [Display(Name = "COnsolidated Salary")]
        //[Required]
        public Nullable<double> ConsolidatedSalary { get; set; }
        [Display(Name = "Place of Posting")]
        //[Required]
        public string PlaceOfPosting { get; set; }
        [Display(Name = "Confirmation Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        [Display(Name = "Year of Last Promotion")]
        //[Required]
        public Nullable<int> YearOfLastPromotion { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Entry Qualification")]
        //[Required]
        public string Qualification { get; set; }
        [Display(Name = "Entry Step")]
        //[Required]
        public Nullable<int> Step { get; set; }
        public Nullable<double> Allowances { get; set; }
        [Display(Name = "Current Rank")]
        //[Required]
        public string CurrentRank { get; set; }
        [Display(Name = "Current Qualification")]
        //[Required]
        public string CurrentQualification { get; set; }
        [Display(Name = "Current Grade Level")]
        //[Required]
        public string CurrentGradeLevel { get; set; }
        [Display(Name = "Current Step")]
        //[Required]
        public Nullable<int> CurrentStep { get; set; }
        [Display(Name = "Signatory To ApptLetter")]
        //[Required]
        public string SignatoryToApptLetter { get; set; }
        [Display(Name = "Current Consolidated Salary")]
        //[Required]
        public Nullable<double> CurrentConsolidatedSalary { get; set; }
        [Display(Name = "Current Designation")]
        //[Required]
        public Nullable<int> CurrentDesignation { get; set; }
    }
}
